//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkyAndBrain {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MotocomSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MotocomSettings defaultInstance = ((MotocomSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MotocomSettings())));
        
        public static MotocomSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetX {
            get {
                return ((double)(this["R1OffsetX"]));
            }
            set {
                this["R1OffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetY {
            get {
                return ((double)(this["R1OffsetY"]));
            }
            set {
                this["R1OffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetZ {
            get {
                return ((double)(this["R1OffsetZ"]));
            }
            set {
                this["R1OffsetZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetRX {
            get {
                return ((double)(this["R1OffsetRX"]));
            }
            set {
                this["R1OffsetRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetRY {
            get {
                return ((double)(this["R1OffsetRY"]));
            }
            set {
                this["R1OffsetRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OffsetRZ {
            get {
                return ((double)(this["R1OffsetRZ"]));
            }
            set {
                this["R1OffsetRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("272.805")]
        public double R1OriginalX {
            get {
                return ((double)(this["R1OriginalX"]));
            }
            set {
                this["R1OriginalX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OriginalY {
            get {
                return ((double)(this["R1OriginalY"]));
            }
            set {
                this["R1OriginalY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("483.095")]
        public double R1OriginalZ {
            get {
                return ((double)(this["R1OriginalZ"]));
            }
            set {
                this["R1OriginalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R1OriginalRX {
            get {
                return ((double)(this["R1OriginalRX"]));
            }
            set {
                this["R1OriginalRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.004")]
        public double R1OriginalRY {
            get {
                return ((double)(this["R1OriginalRY"]));
            }
            set {
                this["R1OriginalRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double R1OriginalRZ {
            get {
                return ((double)(this["R1OriginalRZ"]));
            }
            set {
                this["R1OriginalRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetX {
            get {
                return ((double)(this["R2OffsetX"]));
            }
            set {
                this["R2OffsetX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetY {
            get {
                return ((double)(this["R2OffsetY"]));
            }
            set {
                this["R2OffsetY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetZ {
            get {
                return ((double)(this["R2OffsetZ"]));
            }
            set {
                this["R2OffsetZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetRX {
            get {
                return ((double)(this["R2OffsetRX"]));
            }
            set {
                this["R2OffsetRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetRY {
            get {
                return ((double)(this["R2OffsetRY"]));
            }
            set {
                this["R2OffsetRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OffsetRZ {
            get {
                return ((double)(this["R2OffsetRZ"]));
            }
            set {
                this["R2OffsetRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("874.53")]
        public double R2OriginalX {
            get {
                return ((double)(this["R2OriginalX"]));
            }
            set {
                this["R2OriginalX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OriginalY {
            get {
                return ((double)(this["R2OriginalY"]));
            }
            set {
                this["R2OriginalY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("708.48")]
        public double R2OriginalZ {
            get {
                return ((double)(this["R2OriginalZ"]));
            }
            set {
                this["R2OriginalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public double R2OriginalRX {
            get {
                return ((double)(this["R2OriginalRX"]));
            }
            set {
                this["R2OriginalRX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OriginalRY {
            get {
                return ((double)(this["R2OriginalRY"]));
            }
            set {
                this["R2OriginalRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double R2OriginalRZ {
            get {
                return ((double)(this["R2OriginalRZ"]));
            }
            set {
                this["R2OriginalRZ"] = value;
            }
        }
    }
}
